#!/usr/bin/env python3
import re
import time
import sys
import configparser
import socket
import subprocess
from ES import ES

config = configparser.ConfigParser()
config.read('/etc/monigraf/monigraf.ini')
host = socket.gethostname()

def Check():
    pre_data = {}
    for line in upsLine.splitlines():
        if re.search('LINEV', line): pre_data['inline_volt'] = float(line.split(': ')[1].split(' ')[0])
        elif re.search('BCHARGE', line): pre_data['batt_charge'] = float(line.split(': ')[1].split(' ')[0])
        elif re.search('LOADPCT', line): pre_data['load'] = float(line.split(': ')[1].split(' ')[0])
        elif re.search('TIMELEFT', line): pre_data['time_left'] = float(line.split(': ')[1].split(' ')[0])
    dbinfo.add_listdata("apcups", pre_data)

def Refresh():
    pre_data = {}
    for line in upsLine.splitlines():
        if re.search('SERIALNO', line): pre_data['serial_number'] = line.split(': ')[1]
        elif re.search('MODEL', line): pre_data['model'] = line.split(': ')[1]
        elif re.search('BATTDATE', line): pre_data['batt_date'] = line.split(': ')[1]
        elif re.search('NOMPOWER', line): pre_data['maxpower'] = line.split(': ')[1]
        elif re.search('VERSION', line): pre_data['version'] = line.split(': ')[1]
        elif re.search('UPSNAME', line): pre_data['ups_name'] = line.split(': ')[1]
    dbinfo.add_listdata("apcups", pre_data)

if sys.argv[1] == "refresh":
    dbinfo = ES.ES("monigraf-inventory")
    dbinfo.create_list("apcups")
    listUPS = subprocess.run(['/sbin/apcaccess'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    upsLine = ' '.join(listUPS.split(' '))
    Refresh()
    dbinfo.add_data("host", host)
    dbinfo.send()
    exit()

while True:
    listUPS = subprocess.run(['/sbin/apcaccess'], stdout=subprocess.PIPE).stdout.decode('utf-8')
    upsLine = ' '.join(listUPS.split(' '))
    dbinfo = ES.ES("monigraf-apcups")
    Check()
    dbinfo.add_data("host", host)
    dbinfo.send()
    time.sleep(config.getint('apcups','delay'))
