#!/usr/bin/env python3
import configparser
import subprocess
from datetime import date
import time
import socket
from BodyBuilder import BodyBuilder

config = configparser.ConfigParser()
config.read('/etc/monigraf/monigraf.ini')
host = socket.gethostname()

def Check(domain):
    cert_exp = str(subprocess.run(['/opt/monigraf/check_cert_exp.sh', domain, config['certificates_expiration']['days_before_warning'], config['certificates_expiration']['days_before_critical']], stdout=subprocess.PIPE).stdout.decode('utf-8').rsplit("\n")[0])
    return cert_exp

while True:
    with open(config['certificates_expiration']['domain_file_list']) as domains:
        domain = domains.readline()
        while domain:
            if not domain.startswith('#') and not " " in domain:
                expiration = Check(domain.rstrip("\n"))
                dbinfo = BodyBuilder.BuildBody("certificates_expiration", host)
                dbinfo.add_tag("domain", domain.rstrip("\n").split(':')[0])
                dbinfo.add_field("domain", domain.rstrip("\n").split(':')[0])
                dbinfo.add_field("expiration_time", expiration.split(';')[0])
                dbinfo.add_field("status", expiration.split(';')[1])
                date_year = int(expiration.split(';')[0].split('-')[0])
                date_month = int(expiration.split(';')[0].split('-')[1])
                date_day = int(expiration.split(';')[0].split('-')[2].split(' ')[0])
                dbinfo.add_field("expire_in", str(date(date_year, date_month, date_day) - date.today()).rstrip('-').split(',')[0])
                dbinfo.Add()
                domain = domains.readline()
            else: domain = domains.readline()
    time.sleep(config.getint("certificates_expiration", "delay"))
