#!/usr/bin/env python3
import configparser
import subprocess
from datetime import date
import time
from ES import ES

config = configparser.ConfigParser()
config.read('/etc/monigraf/monigraf.ini')

def Check(domain):
    cert_exp = str(subprocess.run(['/scripts/monigraf/check_cert_exp.sh', domain, config['certificates_expiration']['days_before_warning'], config['certificates_expiration']['days_before_critical']], stdout=subprocess.PIPE).stdout.decode('utf-8').rsplit("\n")[0])

    return cert_exp

while True:
    dbinfo = ES.ES("monigraf-certificates_expiration")
    dbinfo.create_list("domains")
    data = {}
    with open(config['certificates_expiration']['domain_file_list']) as domains:
        domain = domains.readline()
        while domain:
            if not domain.startswith('#') and not " " in domain:
                expiration = Check(domain.rsplit("\n")[0])
                data['domain'] = domain.rsplit("\n")[0].split(':')[0]
                data['expiration_time'] = expiration.split(';')[0]
                data['status'] = expiration.split(';')[1]
                date_year = int(expiration.split(';')[0].split('-')[0])
                date_month = int(expiration.split(';')[0].split('-')[1])
                date_day = int(expiration.split(';')[0].split('-')[2].split(' ')[0])
                data['expire_in'] = str(date.today() - date(date_year, date_month, date_day))
                dbinfo.add_listdata("domains", data)
                domain = domains.readline()
            else: domain = domains.readline()
    dbinfo.send()
    time.sleep(config.getint("certificates_expiration", "delay"))
