#!/usr/bin/env python3
import re
import sys
import configparser
import socket
import subprocess
from ES import ES

config = configparser.ConfigParser()
config.read('/etc/monigraf/monigraf.ini')
host = socket.gethostname()

def Check():
    logs = subprocess.run(['/usr/bin/tail', '-n', listLine[0], listLine[-1]], capture_output=True).stdout.decode('utf-8')
    for log in logs.splitlines():
        dbinfo = ES.ES("monigraf-raw_logs")
        dbinfo.add_data("host", host)
        dbinfo.add_data("file", listLine[-1])
        dbinfo.add_data("message", log)
        dbinfo.send()

while True:
    listLogs = subprocess.run(['/usr/bin/inotifywatch', '-e', 'modify', '-t', config['raw_logs']['delay'], '--fromfile', config['raw_logs']['log_file_list']], capture_output=True)
    output = listLogs.stdout.decode('utf-8')
    for line in output.splitlines():
        listLine = line.split(' ')
        if listLine[0].isdigit():
            Check()
