#!/usr/bin/env python3
import time
import sys
import configparser
import socket
from pySMART import DeviceList
from ES import ES

config = configparser.ConfigParser()
config.read('/etc/monigraf/monigraf.ini')
host = socket.gethostname()

def Check():
    for i in range(len(listDrives)):
        data = {}       # Empty dict to store data to post
        data['device'] = listDrives[i].name
        # Try to get attributes from drives.
        # TBW
        try:
            tbw = int(listDrives[i].attributes[241].raw)
            if tbw < 3000000: tbw = tbw * 1000000000 / 512
        except AttributeError: tbw = -1
        # Temperature
        try: temp = listDrives[i].attributes[194].raw
        except AttributeError: temp = listDrives[i].attributes[190].raw
        data['power_on_hours'] = float(listDrives[i].attributes[9].raw)
        # Health
        try:
            health = str(listDrives[i].attributes[177])
            health = ' '.join(health.split()).split(' ')[2]
        except: health = int(-1)
        data['tbw'] = float(tbw)
        data['temperature'] = int(temp)
        data['health'] = int(health)
        dbinfo.add_listdata("drives", data)

def Refresh():
    for i in range(len(listDrives)):
        data = {}
        # Get drive informations
        data['serial_number'] = listDrives[i].serial
        data['device'] = listDrives[i].name
        data['model'] = listDrives[i].model
        devType = listDrives[i].is_ssd
        if devType: data['type'] = "SSD"
        else: data['type'] = "Hard Drive"
        data['capacity'] = listDrives[i].capacity
        data['firmware'] = listDrives[i].firmware
        dbinfo.add_listdata("drives", data)

if sys.argv[1] == "refresh":
    listDrives = DeviceList().devices
    dbinfo = ES.ES("monigraf-inventory")
    dbinfo.create_list("drives")
    Refresh()
    dbinfo.add_data("host", host)
    dbinfo.send()
    exit()

while True:
    listDrives = DeviceList().devices
    dbinfo = ES.ES("monigraf-smart")
    dbinfo.create_list("drives")
    Check()
    dbinfo.add_data("host", host)
    dbinfo.send()
    time.sleep(config.getint('smart','delay'))
