#!/bin/bash
source /etc/monigraf/monigraf.conf
source /etc/monigraf/modules.d/smart.conf
function Check() {
	while IFS= read -r diskLine; do
		diskLine=`echo "$diskLine" | tr -s ' '`
		uuid=`echo $diskLine | cut -d ' ' -f3`
		if ! [[ "$uuid" =~ "-" ]]; then uuid=`echo $diskLine | cut -d ' ' -f4`; fi
		dev=`echo $diskLine | cut -d ' ' -f1 | tr -d [[:digit:]]`
		tbw=`/usr/sbin/smartctl -A /dev/${dev} | awk '/^241/ { print ""$10"" }'`
		if [[ "$tbw" == "" ]]; then
			tbw=-1
		elif [[ $tbw < 3000000 ]]; then
			tbw=`echo $(($tbw * 1000000000 / 512))`
		fi
		temp=`/usr/sbin/smartctl -A /dev/${dev} | awk '/^194/ { print ""$10"" }'`; if [[ "$temp" == "" ]]; then temp=`/usr/sbin/smartctl -A /dev/${dev} | awk '/^190/ { print ""$10"" }'`; fi
		poweron=`/usr/sbin/smartctl -A /dev/${dev} | awk '/^  9/ { print ""$10"" }'`
		health=`/usr/sbin/smartctl -A /dev/${dev} | awk '/^231/ { print ""$4"" }'`; if [[ "$health" == "" ]]; then health=`/usr/sbin/smartctl -A /dev/${dev} | awk '/^177/ { print ""$4"" }'`; if [[ "$health" == "" ]]; then health=-1; fi; fi
		influx -host $influxserver -username $userdb -password "$password" -database $dbname -execute "INSERT smart,host=$HOSTNAME,dev_uuid=$uuid tbw=$tbw,temp=$temp,power_on_hours=$poweron,life=$health"
	done <<< "$listDisk"
}

function Refresh() {
	influx -host $influxserver -username $userdb -password $password -database $dbname -execute "DELETE FROM smart_info WHERE host = $HOSTNAME"
	while IFS= read -r diskLine; do
                diskLine=`echo "$diskLine" | tr -s ' '`
                uuid=`echo $diskLine | cut -d ' ' -f3`
                if ! [[ "$uuid" =~ "-" ]]; then uuid=`echo $diskLine | cut -d ' ' -f4`; fi
                dev=`echo $diskLine | cut -d ' ' -f1 | tr -d [[:digit:]]`
		devModel=`/usr/sbin/smartctl -i /dev/${dev} | grep "Device Model:" | tr -s ' ' | cut -d ' ' -f3-`
		sn=`/usr/sbin/smartctl -i /dev/${dev} | grep "Serial Number:" | tr -s ' ' | cut -d ' ' -f3`
		type=`/usr/sbin/smartctl -i /dev/${dev} | grep "Rotation Rate:" | tr -s ' ' | cut -d ' ' -f3-`
		capacity=`/usr/sbin/smartctl -i /dev/${dev} | grep "User Capacity:" | tr -s ' ' | cut -d '[' -f2 | cut -d ']' -f1 | tr -d ' '`
                influx -host $influxserver -username $userdb -password $password -database $dbname -execute "INSERT smart_info,host=$HOSTNAME dev_uuid=\"$uuid\",dev_model=\"$devModel\",sn=\"$sn\",capacity=\"$capacity\",dev=\"$dev\",type=\"$type\""
        done <<< "$listDisk"
}
if [[ "$1" == "--refresh" ]]; then
        listDisk=`lsblk -fs --list | grep -E "ext4|LVM2_member" | sort -u | grep ^sd`
	Refresh
        exit
fi
while true; do
	listDisk=`lsblk -fs --list | grep -E "ext4|LVM2_member" | sort -u | grep ^sd`
	Check
	sleep $delay
done
