#!/usr/bin/env python3
import re
import time
import ast
import configparser
import subprocess
from ES import ES

config = configparser.ConfigParser()
config.read('/etc/monigraf/monigraf.ini')

def Check():
    for line in listStats.splitlines():
        if re.search('^time', line): continue
        if re.search('^total', line):
            if re.search('num.queries', line): data['total_queries'] = int(line.split('=')[1])
            elif re.search('num.cachehits', line): data['total_cachehits'] = int(line.split('=')[1])
            elif re.search('num.prefetch', line): data['total_prefetch'] = int(line.split('=')[1])
            elif re.search('recursion.time.avg', line): data['total_recursion_time'] = float(line.split('=')[1])
            elif re.search('tcpusage', line):
                data['total_tcpusage'] = float(line.split('=')[1])
            else: continue

while True:
    dbinfo = ES.ES("monigraf-unbound")
    dbinfo.create_list("dns_servers")
    for host_dns in ast.literal_eval(str(config['unbound']['hosts'])):
        data = {}
        data['host'] = str(host_dns.split('@')[0])
        listStats = subprocess.run(['/usr/sbin/unbound-control', '-s', host_dns, 'stats'], stdout=subprocess.PIPE).stdout.decode('utf-8')
        Check()
        dbinfo.add_listdata("dns_servers", data)
    dbinfo.send()
    time.sleep(config.getint('unbound','delay'))
