#!/usr/bin/python3.7
import time
import sys
import configparser
import ast
import netifaces
import socket
from BodyBuilder import BodyBuilder

config = configparser.ConfigParser()
config.read('/etc/monigraf/monigraf.ini')
host = socket.gethostname()

def Check(net):
    txpath = "/sys/class/net/" + net + "/statistics/tx_bytes"
    rxpath = "/sys/class/net/" + net + "/statistics/rx_bytes"
    macaddr = netifaces.ifaddresses(net)[netifaces.AF_LINK][0]['addr']
    rx_read = open(rxpath, 'r'); tx_read = open(txpath, 'r')
    rx_bytes_last = rx_read.read(); tx_bytes_last = tx_read.read()
    rx_read.close(); tx_read.close()
    # Have to close everytime because the second value will be null.
    time.sleep(1)
    rx_read = open(rxpath, 'r'); tx_read = open(txpath, 'r')
    rx_bytes_now = rx_read.read(); tx_bytes_now = tx_read.read()
    rx_read.close(); tx_read.close()
    rx_bytes = int(float(rx_bytes_now)) - int(float(rx_bytes_last))  # Calculate average bytes per seconds.
    tx_bytes = int(float(tx_bytes_now)) - int(float(tx_bytes_last))     # Calculate average bytes per seconds.
    dbinfo.add_tag("mac", macaddr)
    dbinfo.add_field("rx_bytes", float(rx_bytes))
    dbinfo.add_field("tx_bytes", float(tx_bytes))
    dbinfo.Send()
#def Refresh():
    #influx -host $influxserver -username $userdb -password $password -database $dbname -execute "DELETE FROM network_info WHERE host = $HOSTNAME"
    #while IFS= read -r net; do
        #idKern=`dmesg | grep e1000 | grep "$net" | grep renamed | tr -s ' ' | cut -d ' ' -f4`
        #macaddr=`cat /sys/class/net/${net}/address`		# Retrieve MAC address
        #speed=`cat /sys/class/net/${net}/speed`			# Interface Speed
	#duplex=`cat /sys/class/net/${net}/duplex`		# Duplex mode
	#mtu=`cat /sys/class/net/${net}/mtu`			# MTU
	#controller=`lspci -v -s "$idKern" | grep "Ethernet controller:" | cut -d ':' -f3`
	#driver=`lspci -v -s "$idKern" | grep "Kernel driver in use:" | cut -d ':' -f2`
        #influx -host $influxserver -username $userdb -password $password -database $dbname -execute "INSERT network_info,host=$HOSTNAME mac=\"$macaddr\",speed=\"$speed\",duplex=\"$duplex\",mtu=\"$mtu\",controller=\"$controller\",driver=\"$driver\",dev=\"$net\""
    #done <<< "$listNet"

#if sys.argv[1] is "--refresh":
    #listNet=`netstat -i | awk '{print $1 }' | tail -n +3 | grep -v "lo"`            # Get network interfaces statistics
#    Refresh()
#    exit()

if config['network']['interfaces'] == "all":
    listNet = netifaces.interfaces()            # Get network interfaces
    listNet.remove('lo')                        # Remove loopback interface. Don't want statistic from this one.
else:
    listNet = config['network']['interfaces']

dbinfo = BodyBuilder.BuildBody("network", host)
while True:
    for net in ast.literal_eval(listNet):
        Check(net)
    time.sleep(config.getint('network','delay'))
